steps:
  # This step tells Google to build your Next.js app using Buildpacks
  - name: 'gcr.io/k8s-skaffold/pack'
    args:
      - 'build'
      - 'us-central1-docker.pkg.dev/famous-sheamus-website-462507/cloud-run-source-deploy/famous-sheamus-website:$COMMIT_SHA'
      - '--builder'
      - 'gcr.io/buildpacks/builder:v1'
      - '--network'
      - 'cloudbuild'

# This is the "Magic Fix" that satisfies the error
options:
  logging: CLOUD_LOGGING_ONLY